[package]
name = "loam-sdk-ft"
version = "0.6.6"
edition = "2021"
description = "A Riff for a fungible token"
license = "Apache-2.0"


[dependencies]
loam-sdk = { path = "../loam-sdk", version = "0.6.7", features = [
    "loam-soroban-sdk",
] }

[package.metadata.loam]
riff = true
