[package]
name = "loam-sdk-ft"
version = "0.1.0"
edition = "2021"
description = "A Riff for a fungible token"
license = "Apache-2.0"


[dependencies]
loam-sdk = { workspace = true, features = ["loam-soroban-sdk"] }

[package.metadata.loam]
riff = true
