[package]
name = "loam-sdk-ft"
version.workspace = true
edition = "2021"
description = "A Riff for a fungible token"
license = "Apache-2.0"


[dependencies]
loam-sdk = { workspace = true, version = "0.6.3", features = [
    "loam-soroban-sdk",
] }

[package.metadata.loam]
riff = true
