[workspace]
resolver = "2"
members = ["crates/*", "examples/soroban/*", "test/*"]
exclude = ["test/*"]

[workspace.package]
version = "0.6.2"


[workspace.dependencies]
loam-sdk = { path = "./crates/loam-sdk", version = "*" }
loam-build = { path = "./crates/loam-build", version = "*"}
loam-sdk-core-riff = { path = "./crates/loam-core", version = "*" }
loam-soroban-sdk = { path = "./crates/loam-soroban", version = "*"}
loam-sdk-macro = { path = "./crates/loam-sdk-macro", version = "*"}
loam-sdk-ft = { path = "./crates/loam-ft", version = "*"}

cargo_metadata = "0.15.4"
thiserror = "1.0.38"

[profile.contracts]
inherits = "release"
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = true
panic = "abort"
codegen-units = 1
lto = true
