[workspace]
resolver = "2"
members = ["crates/*", "examples/soroban/*"]
# exclude = ["examples/soroban/*"]


[workspace.dependencies]
loam-sdk = { path = "./crates/loam" }
loam-sdk-core-riffs = { path = "./crates/loam-core" }
loam-soroban-sdk = { path = "./crates/loam-soroban" }
macro-wrapper = { path = "./crates/macro-wrapper" }

[profile.contracts]
inherits = "release"
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = true
panic = "abort"
codegen-units = 1
lto = true
