[workspace]
resolver = "2"
members = ["crates/*", "examples/soroban/*", "crates/macro-wrapper/test/*"]
exclude = ["crates/macro-wrapper/test/*"]


[workspace.dependencies]
loam-sdk = { path = "./crates/loam" }
loam-sdk-core-riff = { path = "./crates/loam-core" }
loam-soroban-sdk = { path = "./crates/loam-soroban" }
macro-wrapper = { path = "./crates/macro-wrapper" }
loam-sdk-ft = { path = "./crates/loam-ft" }

[profile.contracts]
inherits = "release"
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = true
panic = "abort"
codegen-units = 1
lto = true
