[package]
name = "loam-soroban-sdk"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macro-wrapper = { workspace = true }
loam-sdk-core = { workspace = true }

[dependencies.soroban-sdk]
version = "0.7.0"
git = "https://github.com/stellar/rs-soroban-sdk"
rev = "8abd3353c728f09ee1c8a2544f67a853e915afc2"
features = ["alloc"]


[features]
default = []
testutils = ["soroban-sdk/testutils"]
