[package]
name = "loam-soroban-sdk"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macro-wrapper = { workspace = true }

[dependencies.soroban-sdk]
version = "0.7.0"
git = "https://github.com/stellar/rs-soroban-sdk"
rev = "d3c160e54430a37c795ed73618d6e084d6c0d8b6"
features = ["alloc"]


[features]
default = []
testutils = ["soroban-sdk/testutils"]
