[package]
name = "loam-soroban-sdk"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
loam-sdk-macro = { workspace = true }

[dependencies.soroban-sdk]
version = "0.8.4"
git = "https://github.com/stellar/rs-soroban-sdk"
rev = "b983d06ba03f4066886735f7840c9c38d2d71ca9"
features = ["alloc"]


[features]
default = []
testutils = ["soroban-sdk/testutils"]
