[package]
name = "loam-soroban-sdk"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
loam-sdk-macro = { workspace = true }

[dependencies.soroban-sdk]
version = "0.7.0"
git = "https://github.com/stellar/rs-soroban-sdk"
rev = "5d40b4c85660d918339e58aca43036e495a36280"
features = ["alloc"]


[features]
default = []
testutils = ["soroban-sdk/testutils"]
