[package]
name = "loam-sdk"
version.workspace = true
edition = "2021"
description = "SDK  for writing smart contracts"
license = "Apache-2.0"


[lib]
crate-type = ["rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
loam-sdk-macro = { workspace = true, version = "*" }
loam-soroban-sdk = { workspace = true, optional = true, version = "*" }


[features]
default = ["loam-soroban-sdk"]
soroban-sdk-testutils = ["loam-soroban-sdk/testutils"]
