[package]
name = "loam-sdk"
version = "0.6.3"
edition = "2021"
description = "SDK  for writing smart contracts"
license = "Apache-2.0"


[lib]
crate-type = ["rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
loam-sdk-macro = { workspace = true, version = "0.6.3" }
loam-soroban-sdk = { workspace = true, version = "0.6.3", optional = true }


[features]
default = ["loam-soroban-sdk"]
soroban-sdk-testutils = ["loam-soroban-sdk/testutils"]
