[package]
name = "loam-sdk-core-riff"
version = "0.1.0"
edition = "2021"
description = "Core Riff for redeployable contracts"
license = "Apache-2.0"


[dependencies]
loam-sdk = { workspace = true, features = ["loam-soroban-sdk"] }

[package.metadata.loam]
riff = true
