
name: RPC Tests
on:
  push:
    branches: [main, release/**]
  pull_request:

jobs:
  test:
    name: test RPC
    runs-on: moss
    env:
        SOROBAN_RPC_URL: http://localhost:8090/soroban/rpc
        SOROBAN_NETWORK_PASSPHRASE: "Standalone Network ; February 2017"
        SOROBAN_ACCOUNT: default
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - run: rustup update
    - run: rustup target add wasm32-unknown-unknown
    - uses: taiki-e/install-action@just
    - uses: cargo-bins/cargo-binstall@main
    - run: just setup
    - run: just create
    - run: cat .env
    - run: just redeploy
    - run: just test

